server:
  port: 7011   #端口号
spring:
  application:
    name: service-provider-7011  #服务名称
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/   #服务中心地址（单个，多个以逗号分隔）