server:
  port:
    7031
spring:
  application:
    name: cloud-zuul-7031
zuul:
  routes:
    testlgq:     # 路由的 id
      path: /test/**  #映射路径
      url: http://www.lgqoxb.top/blogfront/blog.html#/   #映射路径对应的实际的url地址
      #  访问路径规则 添加 映射路径的规则
#      serviceId: user-service  # 指定服务端的名称